/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      "colors": {
          "on-background": "#f7dcdd",
          "surface-container-high": "#362627",
          "on-secondary-container": "#002a52",
          "on-primary-container": "#5b0017",
          "outline": "#a9898a",
          "primary": "#ffb2b7",
          "surface-container-lowest": "#170b0c",
          "surface-variant": "#413031",
          "on-secondary-fixed-variant": "#004884",
          "primary-fixed-dim": "#ffb2b7",
          "on-primary": "#67001c",
          "on-tertiary": "#003919",
          "on-surface-variant": "#e2bebf",
          "background": "#1d1011",
          "surface": "#1d1011",
          "outline-variant": "#5a4042",
          "primary-fixed": "#ffdadb",
          "on-secondary-fixed": "#001c39",
          "on-surface": "#f7dcdd",
          "surface-bright": "#463536",
          "on-tertiary-fixed": "#00210c",
          "surface-dim": "#1d1011",
          "secondary-fixed-dim": "#a4c9ff",
          "secondary-fixed": "#d4e3ff",
          "on-tertiary-fixed-variant": "#005227",
          "on-error": "#690005",
          "on-primary-fixed-variant": "#91002b",
          "surface-tint": "#ffb2b7",
          "error-container": "#93000a",
          "secondary": "#a4c9ff",
          "inverse-on-surface": "#3d2c2d",
          "tertiary-container": "#25a55a",
          "tertiary": "#66dd8b",
          "surface-container": "#2b1c1d",
          "error": "#ffb4ab",
          "on-secondary": "#00315d",
          "on-primary-fixed": "#40000e",
          "primary-container": "#fc536d",
          "tertiary-fixed": "#83fba5",
          "tertiary-fixed-dim": "#66dd8b",
          "inverse-primary": "#b71d3f",
          "secondary-container": "#3b93f3",
          "surface-container-highest": "#413031",
          "inverse-surface": "#f7dcdd",
          "on-error-container": "#ffdad6",
          "surface-container-low": "#261819",
          "on-tertiary-container": "#003115"
      },
      "borderRadius": {
          "DEFAULT": "0.25rem",
          "lg": "0.5rem",
          "xl": "0.75rem",
          "full": "9999px"
      },
      "spacing": {
          "2xl": "48px",
          "3xl": "64px",
          "md": "16px",
          "base": "4px",
          "lg": "24px",
          "sm": "12px",
          "xl": "32px",
          "xs": "8px"
      },
      "fontFamily": {
          "display-lg": ["Inter", "sans-serif"],
          "body-md": ["Inter", "sans-serif"],
          "caption": ["Inter", "sans-serif"],
          "label-md": ["Inter", "sans-serif"],
          "headline-lg-mobile": ["Inter", "sans-serif"],
          "headline-md": ["Inter", "sans-serif"],
          "headline-lg": ["Inter", "sans-serif"],
          "title-lg": ["Inter", "sans-serif"],
          "body-lg": ["Inter", "sans-serif"]
      },
      "fontSize": {
          "display-lg": ["48px", {"lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "700"}],
          "body-md": ["14px", {"lineHeight": "20px", "fontWeight": "400"}],
          "caption": ["12px", {"lineHeight": "16px", "fontWeight": "300"}],
          "label-md": ["12px", {"lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "600"}],
          "headline-lg-mobile": ["24px", {"lineHeight": "32px", "fontWeight": "600"}],
          "headline-md": ["24px", {"lineHeight": "32px", "fontWeight": "600"}],
          "headline-lg": ["32px", {"lineHeight": "40px", "letterSpacing": "-0.01em", "fontWeight": "600"}],
          "title-lg": ["20px", {"lineHeight": "28px", "fontWeight": "500"}],
          "body-lg": ["16px", {"lineHeight": "24px", "fontWeight": "400"}]
      }
    },
  },
  plugins: [],
}
